export const SEARCH_FOCUS = "HEADER_SEARCH_FOCUS";
export const SEARCH_BLUR = "HEADER_SEARCH_BLUR";
export const CHANGE_LIST = "CHANGE_LIST";
export const MOUSE_ENTER = "MOUSE_ENTER";
export const MOUSE_LEAVE = "MOUSE_LEAVE";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_HOME_DATA = "CHANGE_HOME_DATA";
export const ADD_HOME_LIST = "ADD_HOME_LIST";